/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionButton: typeof import('./src/components/Search/src/components/ActionButton.vue')['default']
    Backtop: typeof import('./src/components/Backtop/src/Backtop.vue')['default']
    Breadcrumb: typeof import('./src/components/Breadcrumb/src/Breadcrumb.vue')['default']
    Button: typeof import('./src/components/Button/src/Button.vue')['default']
    Collapse: typeof import('./src/components/Collapse/src/Collapse.vue')['default']
    ColorRadioPicker: typeof import('./src/components/Setting/src/components/ColorRadioPicker.vue')['default']
    ColumnSetting: typeof import('./src/components/Table/src/components/ColumnSetting.vue')['default']
    ConfigGlobal: typeof import('./src/components/ConfigGlobal/src/ConfigGlobal.vue')['default']
    ContentDetailWrap: typeof import('./src/components/ContentDetailWrap/src/ContentDetailWrap.vue')['default']
    ContentWrap: typeof import('./src/components/ContentWrap/src/ContentWrap.vue')['default']
    ContextMenu: typeof import('./src/components/ContextMenu/src/ContextMenu.vue')['default']
    Descriptions: typeof import('./src/components/Descriptions/src/Descriptions.vue')['default']
    Dialog: typeof import('./src/components/Dialog/src/Dialog.vue')['default']
    EditableTable: typeof import('./src/components/EditableTable/src/EditableTable.vue')['default']
    Editor: typeof import('./src/components/Editor/src/Editor.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElTable: typeof import('element-plus/es')['ElTable']
    Error: typeof import('./src/components/Error/src/Error.vue')['default']
    Footer: typeof import('./src/components/Footer/src/Footer.vue')['default']
    Form: typeof import('./src/components/Form/src/Form.vue')['default']
    Icon: typeof import('./src/components/Icon/src/Icon.vue')['default']
    InputPassword: typeof import('./src/components/InputPassword/src/InputPassword.vue')['default']
    InterfaceDisplay: typeof import('./src/components/Setting/src/components/InterfaceDisplay.vue')['default']
    LayoutRadioPicker: typeof import('./src/components/Setting/src/components/LayoutRadioPicker.vue')['default']
    LocaleDropdown: typeof import('./src/components/LocaleDropdown/src/LocaleDropdown.vue')['default']
    LockDialog: typeof import('./src/components/UserInfo/src/components/LockDialog.vue')['default']
    LockPage: typeof import('./src/components/UserInfo/src/components/LockPage.vue')['default']
    Logo: typeof import('./src/components/Logo/src/Logo.vue')['default']
    Menu: typeof import('./src/components/Menu/src/Menu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Screenfull: typeof import('./src/components/Screenfull/src/Screenfull.vue')['default']
    Search: typeof import('./src/components/Search/src/Search.vue')['default']
    Setting: typeof import('./src/components/Setting/src/Setting.vue')['default']
    SizeDropdown: typeof import('./src/components/SizeDropdown/src/SizeDropdown.vue')['default']
    Table: typeof import('./src/components/Table/src/Table.vue')['default']
    TableActions: typeof import('./src/components/Table/src/components/TableActions.vue')['default']
    TabMenu: typeof import('./src/components/TabMenu/src/TabMenu.vue')['default']
    TagsView: typeof import('./src/components/TagsView/src/TagsView.vue')['default']
    ThemeSwitch: typeof import('./src/components/ThemeSwitch/src/ThemeSwitch.vue')['default']
    UserInfo: typeof import('./src/components/UserInfo/src/UserInfo.vue')['default']
    VideoPlayer: typeof import('./src/components/VideoPlayer/src/VideoPlayer.vue')['default']
    VideoPlayerViewer: typeof import('./src/components/VideoPlayerViewer/src/VideoPlayerViewer.vue')['default']
  }
}
